sudo: true

dist: trusty

language: cpp

compiler: gcc

install:
  - sudo apt-get install -y g++ python3 openjdk-7-jdk
  - export CXX="g++-4.8"

script:
  - cd ~/build/HaliteChallenge/Halite/airesources/Java
  - javac MyBot.java

  - cd ../C++
  - g++ -std=c++11 MyBot.cpp -o MyBot.o

  - cd ~/build/HaliteChallenge/Halite/halite/environment
  - make
  - ./environment -d 10 10 "python3 ../../airesources/Python/MyBot.py" "cd ../../airesources/Java; java MyBot" "../../airesources/C++/MyBot.o"

notifications:
    slack: halite:HnrNM3effc9q8ZVvT7PqsSYC
