sudo: required

dist: trusty

language: cpp

services: 
  - mysql

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test 
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.9
  - export CXX="g++-4.9" 
  - g++ -v

  - cd ~/build/HaliteChallenge/Halite/tests
  - cp travisTests.ini tests.ini
  - cp travisTests.ini ../halite.ini
 
  - cd ~/build/HaliteChallenge/Halite/website
  - sudo ./install.sh

  - cd ~/build/HaliteChallenge/Halite/worker
  - sudo docker build -t 'mntruell/halite_sandbox:latest' - < Dockerfile
  - sudo ./install.sh 123

  - cd ~/build/HaliteChallenge/Halite/tests
  - sudo ./install.sh
  - g++ -v
  - echo $CXX; 

script:
  - cd ~/build/HaliteChallenge/Halite/tests/
  - sudo ./runTests.sh

notifications:
    slack: halite:HnrNM3effc9q8ZVvT7PqsSYC
